[private]
default:
    @just --list

# install default flatpaks
install-flatpaks:
    xargs -a {{justfile_directory()}}/flatpaks flatpak --system -y install

# initialize sshkey and configure git
setup-git:
    @/usr/libexec/tuque-os/setup-git.sh

# configure capslock key as an additional ctrl
caps-as-ctrl:
	gsettings set org.gnome.desktop.input-sources xkb-options \[\'caps:ctrl_modifier\'\]

# install the firefox policy file as a flatpak extension
firefox-policy:
    #!/usr/bin/bash
    FLATPAK_POLICIES="/var/lib/flatpak/extension/org.mozilla.firefox.systemconfig/x86_64/stable/policies/policies.json"

    mkdir -p "$FLATPAK_POLICIES"
    cp /usr/share/tuque-os/firefox-policies.json "$FLATPAK_POLICIES"
