[private]
default:
    @just --list

install-flatpaks:
    xargs -a {{justfile_directory()}}/flatpaks flatpak --system -y install

setup-git:
    @/usr/libexec/tuque-os/setup-git.sh

# configure capslock key as an additional ctrl
caps-as-ctrl:
	gsettings set org.gnome.desktop.input-sources xkb-options \[\'caps:ctrl_modifier\'\]
