[private]
default:
    @just --list

# install default flatpaks
install-flatpaks:
    xargs -a {{justfile_directory()}}/flatpaks flatpak --system -y install

# initialize sshkey and configure git
setup-git:
    @/usr/libexec/tuque-os/setup-git.sh

# initialize settings and extensions
setup-vscodium:
    @/usr/libexec/tuque-os/setup-vscodium.sh

# configure capslock key as an additional ctrl
caps-as-ctrl:
	gsettings set org.gnome.desktop.input-sources xkb-options \[\'caps:ctrl_modifier\'\]

# create default toolbox container
toolbox:
    toolbox create --container dev
